version: 2
updates:
  - package-ecosystem: github-actions
    directory: ""
    target-branch: develop
    schedule:
      interval: weekly
  - package-ecosystem: gitsubmodule
    directory: cicd/version
    target-branch: develop
    schedule:
      interval: weekly
